# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_design/form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1276, 1180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(40, 43, 48);\n"
"    color: rgb(153, 170, 181);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(60, 63, 68);\n"
"    color: rgb(153, 170, 181);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 73, 78);\n"
"    color: rgb(255, 255, 255); /* Make text whiter when hovering */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(50, 53, 58);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: rgb(153, 170, 181);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(153, 170, 181);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SaveDarkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveDarkBtn.setGeometry(QtCore.QRect(30, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SaveDarkBtn.setFont(font)
        self.SaveDarkBtn.setObjectName("SaveDarkBtn")
        self.LasernmBtn = QtWidgets.QLineEdit(self.centralwidget)
        self.LasernmBtn.setGeometry(QtCore.QRect(150, 50, 101, 41))
        self.LasernmBtn.setObjectName("LasernmBtn")
        self.OpenCommBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenCommBtn.setGeometry(QtCore.QRect(30, 100, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OpenCommBtn.setFont(font)
        self.OpenCommBtn.setObjectName("OpenCommBtn")
        self.CloseCommBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CloseCommBtn.setGeometry(QtCore.QRect(30, 150, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CloseCommBtn.setFont(font)
        self.CloseCommBtn.setObjectName("CloseCommBtn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 200, 221, 391))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.IntTimeEdt = QtWidgets.QLineEdit(self.groupBox)
        self.IntTimeEdt.setGeometry(QtCore.QRect(20, 60, 101, 41))
        self.IntTimeEdt.setObjectName("IntTimeEdt")
        self.NumAvgEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumAvgEdt.setGeometry(QtCore.QRect(20, 150, 101, 41))
        self.NumAvgEdt.setObjectName("NumAvgEdt")
        self.NumTrigMeasEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumTrigMeasEdt.setGeometry(QtCore.QRect(20, 240, 101, 41))
        self.NumTrigMeasEdt.setObjectName("NumTrigMeasEdt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 159, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.NumTrigSelEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumTrigSelEdt.setGeometry(QtCore.QRect(20, 330, 101, 41))
        self.NumTrigSelEdt.setObjectName("NumTrigSelEdt")
        self.StartMeasBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartMeasBtn.setGeometry(QtCore.QRect(30, 610, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartMeasBtn.setFont(font)
        self.StartMeasBtn.setObjectName("StartMeasBtn")
        self.StopMeasBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StopMeasBtn.setGeometry(QtCore.QRect(30, 680, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StopMeasBtn.setFont(font)
        self.StopMeasBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 50, 50);\n"
"    color: white;\n"
"    border: 1px solid rgb(150, 30, 30);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 70, 70);\n"
"}\n"
"")
        self.StopMeasBtn.setObjectName("StopMeasBtn")
        self.TrigSaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TrigSaveBtn.setGeometry(QtCore.QRect(30, 750, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TrigSaveBtn.setFont(font)
        self.TrigSaveBtn.setObjectName("TrigSaveBtn")
        self.plot = Plot(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(280, 50, 1081, 821))
        self.plot.setObjectName("plot")
        self.Avg200StartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.Avg200StartBtn.setGeometry(QtCore.QRect(30, 820, 221, 51))
        self.Avg200StartBtn.setObjectName("Avg200StartBtn")
        self.AvgPresetEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.AvgPresetEdit.setGeometry(QtCore.QRect(30, 890, 113, 27))
        self.AvgPresetEdit.setObjectName("AvgPresetEdit")
        self.ShutterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ShutterBtn.setGeometry(QtCore.QRect(30, 940, 221, 51))
        self.ShutterBtn.setObjectName("ShutterBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.SaveDarkBtn, self.OpenCommBtn)
        MainWindow.setTabOrder(self.OpenCommBtn, self.CloseCommBtn)
        MainWindow.setTabOrder(self.CloseCommBtn, self.IntTimeEdt)
        MainWindow.setTabOrder(self.IntTimeEdt, self.NumAvgEdt)
        MainWindow.setTabOrder(self.NumAvgEdt, self.NumTrigMeasEdt)
        MainWindow.setTabOrder(self.NumTrigMeasEdt, self.StartMeasBtn)
        MainWindow.setTabOrder(self.StartMeasBtn, self.StopMeasBtn)
        MainWindow.setTabOrder(self.StopMeasBtn, self.TrigSaveBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SaveDarkBtn.setText(_translate("MainWindow", "Dark"))
        self.OpenCommBtn.setText(_translate("MainWindow", "Open Communication"))
        self.CloseCommBtn.setText(_translate("MainWindow", "Close Communication"))
        self.groupBox.setTitle(_translate("MainWindow", "Measurement Parameters"))
        self.label.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_2.setText(_translate("MainWindow", "Number of Averages"))
        self.label_3.setText(_translate("MainWindow", "All Trigger Samples"))
        self.label_4.setText(_translate("MainWindow", "Selected Trigger Samples"))
        self.StartMeasBtn.setText(_translate("MainWindow", "Start Measurements"))
        self.StopMeasBtn.setText(_translate("MainWindow", "Stop Measurements"))
        self.TrigSaveBtn.setText(_translate("MainWindow", "Trigger Start"))
        self.Avg200StartBtn.setText(_translate("MainWindow", "200 Avg Start"))
        self.AvgPresetEdit.setText(_translate("MainWindow", "200"))
        self.ShutterBtn.setText(_translate("MainWindow", "Shutter Closed"))
from plot import Plot
