# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_design/form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(40, 43, 48);\n"
"    color: rgb(153, 170, 181);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(60, 63, 68);\n"
"    color: rgb(153, 170, 181);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 73, 78);\n"
"    color: rgb(255, 255, 255); /* Make text whiter when hovering */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(50, 53, 58);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: rgb(153, 170, 181);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(153, 170, 181);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SaveDarkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveDarkBtn.setGeometry(QtCore.QRect(30, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SaveDarkBtn.setFont(font)
        self.SaveDarkBtn.setObjectName("SaveDarkBtn")
        self.LasernmBtn = QtWidgets.QLineEdit(self.centralwidget)
        self.LasernmBtn.setGeometry(QtCore.QRect(150, 50, 101, 41))
        self.LasernmBtn.setObjectName("LasernmBtn")
        self.OpenCommBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenCommBtn.setGeometry(QtCore.QRect(30, 100, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OpenCommBtn.setFont(font)
        self.OpenCommBtn.setObjectName("OpenCommBtn")
        self.CloseCommBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CloseCommBtn.setGeometry(QtCore.QRect(30, 150, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CloseCommBtn.setFont(font)
        self.CloseCommBtn.setObjectName("CloseCommBtn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 200, 221, 391))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.IntTimeEdt = QtWidgets.QLineEdit(self.groupBox)
        self.IntTimeEdt.setGeometry(QtCore.QRect(20, 60, 101, 41))
        self.IntTimeEdt.setObjectName("IntTimeEdt")
        self.NumAvgEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumAvgEdt.setGeometry(QtCore.QRect(20, 150, 101, 41))
        self.NumAvgEdt.setObjectName("NumAvgEdt")
        self.NumTrigMeasEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumTrigMeasEdt.setGeometry(QtCore.QRect(20, 240, 101, 41))
        self.NumTrigMeasEdt.setObjectName("NumTrigMeasEdt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 159, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.NumTrigSelEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumTrigSelEdt.setGeometry(QtCore.QRect(20, 330, 101, 41))
        self.NumTrigSelEdt.setObjectName("NumTrigSelEdt")
        self.StartMeasBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartMeasBtn.setGeometry(QtCore.QRect(30, 610, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartMeasBtn.setFont(font)
        self.StartMeasBtn.setObjectName("StartMeasBtn")
        self.StopMeasBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StopMeasBtn.setGeometry(QtCore.QRect(30, 680, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StopMeasBtn.setFont(font)
        self.StopMeasBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 50, 50);\n"
"    color: white;\n"
"    border: 1px solid rgb(150, 30, 30);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 70, 70);\n"
"}\n"
"")
        self.StopMeasBtn.setObjectName("StopMeasBtn")
        self.TrigSaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TrigSaveBtn.setGeometry(QtCore.QRect(30, 750, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TrigSaveBtn.setFont(font)
        self.TrigSaveBtn.setObjectName("TrigSaveBtn")
        self.plot = Plot(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(280, 50, 1361, 941))
        self.plot.setObjectName("plot")
        self.Avg200StartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.Avg200StartBtn.setGeometry(QtCore.QRect(30, 820, 221, 51))
        self.Avg200StartBtn.setObjectName("Avg200StartBtn")
        self.AvgPresetEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.AvgPresetEdit.setGeometry(QtCore.QRect(30, 890, 113, 27))
        self.AvgPresetEdit.setObjectName("AvgPresetEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1670, 50, 221, 431))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.label_5.setObjectName("label_5")
        self.InitShutter = QtWidgets.QPushButton(self.groupBox_2)
        self.InitShutter.setGeometry(QtCore.QRect(20, 70, 181, 31))
        self.InitShutter.setObjectName("InitShutter")
        self.ShutterBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.ShutterBtn.setGeometry(QtCore.QRect(20, 140, 171, 31))
        self.ShutterBtn.setObjectName("ShutterBtn")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 201, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 201, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 180, 191, 16))
        self.label_8.setObjectName("label_8")
        self.MeasureLatencyBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.MeasureLatencyBtn.setGeometry(QtCore.QRect(20, 308, 81, 31))
        self.MeasureLatencyBtn.setObjectName("MeasureLatencyBtn")
        self.LatencyResultLabel = QtWidgets.QLabel(self.groupBox_2)
        self.LatencyResultLabel.setGeometry(QtCore.QRect(120, 310, 71, 31))
        self.LatencyResultLabel.setObjectName("LatencyResultLabel")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 350, 201, 16))
        self.label_10.setObjectName("label_10")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 400, 191, 17))
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setObjectName("checkBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 370, 201, 16))
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 200, 181, 16))
        self.label_9.setObjectName("label_9")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(20, 220, 181, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(20, 240, 181, 16))
        self.label_21.setObjectName("label_21")
        self.LatencyWavelength = QtWidgets.QLineEdit(self.groupBox_2)
        self.LatencyWavelength.setGeometry(QtCore.QRect(20, 270, 51, 31))
        self.LatencyWavelength.setObjectName("LatencyWavelength")
        self.LatencyPercentage = QtWidgets.QLineEdit(self.groupBox_2)
        self.LatencyPercentage.setGeometry(QtCore.QRect(120, 270, 51, 31))
        self.LatencyPercentage.setObjectName("LatencyPercentage")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(80, 280, 21, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(180, 280, 21, 16))
        self.label_23.setObjectName("label_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1670, 490, 221, 461))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 201, 16))
        self.label_15.setObjectName("label_15")
        self.RotationTarget = QtWidgets.QLineEdit(self.groupBox_3)
        self.RotationTarget.setGeometry(QtCore.QRect(120, 140, 71, 31))
        self.RotationTarget.setObjectName("RotationTarget")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.label_14.setObjectName("label_14")
        self.InitRotation = QtWidgets.QPushButton(self.groupBox_3)
        self.InitRotation.setGeometry(QtCore.QRect(24, 70, 171, 31))
        self.InitRotation.setObjectName("InitRotation")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 201, 16))
        self.label_13.setObjectName("label_13")
        self.MoveRotation = QtWidgets.QPushButton(self.groupBox_3)
        self.MoveRotation.setGeometry(QtCore.QRect(20, 140, 81, 31))
        self.MoveRotation.setObjectName("MoveRotation")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 171, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(20, 210, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 250, 171, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 280, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 320, 181, 16))
        self.label_17.setObjectName("label_17")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 350, 171, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 430, 191, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 380, 201, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 400, 211, 16))
        self.label_19.setObjectName("label_19")
        self.SimulateData = QtWidgets.QCheckBox(self.centralwidget)
        self.SimulateData.setGeometry(QtCore.QRect(1670, 970, 231, 21))
        self.SimulateData.setObjectName("SimulateData")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.SaveDarkBtn, self.OpenCommBtn)
        MainWindow.setTabOrder(self.OpenCommBtn, self.CloseCommBtn)
        MainWindow.setTabOrder(self.CloseCommBtn, self.IntTimeEdt)
        MainWindow.setTabOrder(self.IntTimeEdt, self.NumAvgEdt)
        MainWindow.setTabOrder(self.NumAvgEdt, self.NumTrigMeasEdt)
        MainWindow.setTabOrder(self.NumTrigMeasEdt, self.StartMeasBtn)
        MainWindow.setTabOrder(self.StartMeasBtn, self.StopMeasBtn)
        MainWindow.setTabOrder(self.StopMeasBtn, self.TrigSaveBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SaveDarkBtn.setText(_translate("MainWindow", "Dark"))
        self.OpenCommBtn.setText(_translate("MainWindow", "Open Communication"))
        self.CloseCommBtn.setText(_translate("MainWindow", "Close Communication"))
        self.groupBox.setTitle(_translate("MainWindow", "Measurement Parameters"))
        self.label.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_2.setText(_translate("MainWindow", "Number of Averages"))
        self.label_3.setText(_translate("MainWindow", "All Trigger Samples"))
        self.label_4.setText(_translate("MainWindow", "Selected Trigger Samples"))
        self.StartMeasBtn.setText(_translate("MainWindow", "Start Measurements"))
        self.StopMeasBtn.setText(_translate("MainWindow", "Stop Measurements"))
        self.TrigSaveBtn.setText(_translate("MainWindow", "Trigger Start"))
        self.Avg200StartBtn.setText(_translate("MainWindow", "200 Avg Start"))
        self.AvgPresetEdit.setText(_translate("MainWindow", "200"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Shutter, ND filter rotation setup"))
        self.label_5.setText(_translate("MainWindow", "Initialisation (run this first). Will move "))
        self.InitShutter.setText(_translate("MainWindow", "Initialise shutter"))
        self.ShutterBtn.setText(_translate("MainWindow", "Shutter Closed"))
        self.label_6.setText(_translate("MainWindow", "Manual Control"))
        self.label_7.setText(_translate("MainWindow", "shutter to home position (open)"))
        self.label_8.setText(_translate("MainWindow", "Shutter calibration"))
        self.MeasureLatencyBtn.setText(_translate("MainWindow", "Measure delay"))
        self.LatencyResultLabel.setText(_translate("MainWindow", "-- ms"))
        self.label_10.setText(_translate("MainWindow", "Enable logic (when measurement started"))
        self.checkBox.setText(_translate("MainWindow", "Enable shutter logic"))
        self.label_11.setText(_translate("MainWindow", "close shutter and measure after delay"))
        self.label_9.setText(_translate("MainWindow", "Delay will be measured when counts"))
        self.label_20.setText(_translate("MainWindow", "at [wavelength] drop to [percentage]"))
        self.label_21.setText(_translate("MainWindow", "of counts when button was pressed."))
        self.LatencyWavelength.setText(_translate("MainWindow", "532"))
        self.LatencyPercentage.setText(_translate("MainWindow", "10"))
        self.label_22.setText(_translate("MainWindow", "nm"))
        self.label_23.setText(_translate("MainWindow", "%"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ND filter rotation stage setup"))
        self.label_15.setText(_translate("MainWindow", "stage to home position (0 degrees)"))
        self.RotationTarget.setText(_translate("MainWindow", "--"))
        self.label_14.setText(_translate("MainWindow", "Initialisation (run this first). Will move "))
        self.InitRotation.setText(_translate("MainWindow", "Initialise rotation stage"))
        self.label_13.setText(_translate("MainWindow", "Manual control"))
        self.MoveRotation.setText(_translate("MainWindow", "Move to (deg):"))
        self.label_12.setText(_translate("MainWindow", "Target frequency (nm)"))
        self.lineEdit.setText(_translate("MainWindow", "1064"))
        self.label_16.setText(_translate("MainWindow", "Target power (counts)"))
        self.lineEdit_3.setText(_translate("MainWindow", "10000"))
        self.label_17.setText(_translate("MainWindow", "Reverse rotation direction"))
        self.checkBox_2.setText(_translate("MainWindow", "not reversed"))
        self.checkBox_3.setText(_translate("MainWindow", "Enable rotation stage logic"))
        self.label_18.setText(_translate("MainWindow", "Enable logic (rotates ND filter to maintain"))
        self.label_19.setText(_translate("MainWindow", "set power at set frequency)"))
        self.SimulateData.setText(_translate("MainWindow", "Simulate spectrometer data (for debug)"))
from plot import Plot


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
