# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_design/shutter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShutterDialog(object):
    def setupUi(self, ShutterDialog):
        ShutterDialog.setObjectName("ShutterDialog")
        ShutterDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(ShutterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.MeasureLatencyBtn = QtWidgets.QPushButton(ShutterDialog)
        self.MeasureLatencyBtn.setGeometry(QtCore.QRect(20, 70, 141, 27))
        self.MeasureLatencyBtn.setObjectName("MeasureLatencyBtn")
        self.LatencyResultLabel = QtWidgets.QLabel(ShutterDialog)
        self.LatencyResultLabel.setGeometry(QtCore.QRect(190, 70, 191, 31))
        self.LatencyResultLabel.setObjectName("LatencyResultLabel")
        self.SimulateData = QtWidgets.QCheckBox(ShutterDialog)
        self.SimulateData.setGeometry(QtCore.QRect(20, 120, 231, 25))
        self.SimulateData.setObjectName("SimulateData")
        self.ShutterOpen = QtWidgets.QPushButton(ShutterDialog)
        self.ShutterOpen.setGeometry(QtCore.QRect(20, 20, 101, 27))
        self.ShutterOpen.setObjectName("ShutterOpen")
        self.ShutterClose = QtWidgets.QPushButton(ShutterDialog)
        self.ShutterClose.setGeometry(QtCore.QRect(140, 20, 101, 27))
        self.ShutterClose.setObjectName("ShutterClose")

        self.retranslateUi(ShutterDialog)
        self.buttonBox.accepted.connect(ShutterDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ShutterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ShutterDialog)

    def retranslateUi(self, ShutterDialog):
        _translate = QtCore.QCoreApplication.translate
        ShutterDialog.setWindowTitle(_translate("ShutterDialog", "Dialog"))
        self.MeasureLatencyBtn.setText(_translate("ShutterDialog", "Measure Latency"))
        self.LatencyResultLabel.setText(_translate("ShutterDialog", "-- ms"))
        self.SimulateData.setText(_translate("ShutterDialog", "Simulate Spectrometer Data"))
        self.ShutterOpen.setText(_translate("ShutterDialog", "Open Shutter"))
        self.ShutterClose.setText(_translate("ShutterDialog", "Close Shutter"))
