# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_design/shutter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShutterDialog(object):
    def setupUi(self, ShutterDialog):
        ShutterDialog.setObjectName("ShutterDialog")
        ShutterDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(ShutterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.MeasureLatencyBtn = QtWidgets.QPushButton(ShutterDialog)
        self.MeasureLatencyBtn.setGeometry(QtCore.QRect(10, 190, 141, 27))
        self.MeasureLatencyBtn.setObjectName("MeasureLatencyBtn")
        self.LatencyResultLabel = QtWidgets.QLabel(ShutterDialog)
        self.LatencyResultLabel.setGeometry(QtCore.QRect(180, 190, 101, 31))
        self.LatencyResultLabel.setObjectName("LatencyResultLabel")
        self.SimulateData = QtWidgets.QCheckBox(ShutterDialog)
        self.SimulateData.setGeometry(QtCore.QRect(0, 260, 231, 25))
        self.SimulateData.setObjectName("SimulateData")
        self.ShutterOpen = QtWidgets.QPushButton(ShutterDialog)
        self.ShutterOpen.setGeometry(QtCore.QRect(10, 150, 101, 27))
        self.ShutterOpen.setObjectName("ShutterOpen")
        self.ShutterClose = QtWidgets.QPushButton(ShutterDialog)
        self.ShutterClose.setGeometry(QtCore.QRect(120, 150, 101, 27))
        self.ShutterClose.setObjectName("ShutterClose")
        self.label = QtWidgets.QLabel(ShutterDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ShutterDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 371, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ShutterDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 361, 21))
        self.label_3.setObjectName("label_3")
        self.InitShutter = QtWidgets.QPushButton(ShutterDialog)
        self.InitShutter.setGeometry(QtCore.QRect(10, 80, 181, 27))
        self.InitShutter.setObjectName("InitShutter")
        self.InitRotation = QtWidgets.QPushButton(ShutterDialog)
        self.InitRotation.setGeometry(QtCore.QRect(200, 80, 181, 27))
        self.InitRotation.setObjectName("InitRotation")
        self.ShutterStatus = QtWidgets.QLabel(ShutterDialog)
        self.ShutterStatus.setGeometry(QtCore.QRect(10, 120, 181, 19))
        self.ShutterStatus.setObjectName("ShutterStatus")
        self.RotationStatus = QtWidgets.QLabel(ShutterDialog)
        self.RotationStatus.setGeometry(QtCore.QRect(200, 120, 181, 19))
        self.RotationStatus.setObjectName("RotationStatus")
        self.MoveRotation = QtWidgets.QPushButton(ShutterDialog)
        self.MoveRotation.setGeometry(QtCore.QRect(230, 150, 111, 27))
        self.MoveRotation.setObjectName("MoveRotation")
        self.RotationTarget = QtWidgets.QLineEdit(ShutterDialog)
        self.RotationTarget.setGeometry(QtCore.QRect(350, 150, 41, 27))
        self.RotationTarget.setObjectName("RotationTarget")

        self.retranslateUi(ShutterDialog)
        self.buttonBox.accepted.connect(ShutterDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ShutterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ShutterDialog)

    def retranslateUi(self, ShutterDialog):
        _translate = QtCore.QCoreApplication.translate
        ShutterDialog.setWindowTitle(_translate("ShutterDialog", "Dialog"))
        self.MeasureLatencyBtn.setText(_translate("ShutterDialog", "Measure Latency"))
        self.LatencyResultLabel.setText(_translate("ShutterDialog", "-- ms"))
        self.SimulateData.setText(_translate("ShutterDialog", "Simulate Spectrometer Data"))
        self.ShutterOpen.setText(_translate("ShutterDialog", "Open Shutter"))
        self.ShutterClose.setText(_translate("ShutterDialog", "Close Shutter"))
        self.label.setText(_translate("ShutterDialog", "Make sure shutter is connected to AXIS 1 and"))
        self.label_2.setText(_translate("ShutterDialog", "rotation stage to AXIS 2 - They will burn up if wired"))
        self.label_3.setText(_translate("ShutterDialog", "to the wrong ports!!!"))
        self.InitShutter.setText(_translate("ShutterDialog", "Initialise Shutter"))
        self.InitRotation.setText(_translate("ShutterDialog", "Initialise Rotation Stage"))
        self.ShutterStatus.setText(_translate("ShutterDialog", "Shutter status"))
        self.RotationStatus.setText(_translate("ShutterDialog", "Rotation status"))
        self.MoveRotation.setText(_translate("ShutterDialog", "Move to (deg):"))
